defaults:
  - _self_
  - workload: language #language, vision
  # - override hydra/hydra_logging: disabled  
  # - override hydra/job_logging: disabled


cache_address: 10.0.24.192:6378  #10.0.24.192:6378 # '10.0.24.192:6378' # '10.0.29.229:6378' 10.0.20.157:6378'
simulate_mode: False
batch_creation_lambda: 'superdataloader-CreateBatchFunction-WlTEivefOYJK'
testing_locally: False
sam_local_url: 'http://localhost:3000'
sam_local_endpoint: '/create_batch'
num_dataset_partitions: 1

hydra:
  run:
    dir: .  # Current directory or a specific directory where Ray Tune expects to find it
  sweep:
    dir: .  # Same as above
  output_subdir: null
  job_logging:
    level: DISABLE  # Disable job-specific logging
  hydra_logging:
    level: DISABLE  # Disable Hydra-specific logging
